### ISSUE TITLE
Proxy meshes of the synthetic scenes?

### ISSUE THREAD

**Issue by szx0112** [nmoehrle/uavmvs#15]
Hi,

Where can we find the proxy meshes of the synthetic scenes (e.g. NY-1, CA-1) discussed in the article? I could not find them either here or through the project page.

Any comment is really appreciated.

**Comment by szx0112** [comment]
I find them in the 'more files' ...

**Comment by HZhang1003** [comment]
> I find them in the 'more files' ...

Hello, I also cannot find the synthesis scene meshes that can be used as the ground truth. Where can I find the 'more files' you mentioned?

Looking forward to your reply. Thank you.
