### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by EthanChen8158** [nmoehrle/uavmvs#19]
when I ran the generate_proxy_mesh to generate a mesh from a point cloud，I got this error 

Received signal SIGSEGV (segmentation fault)
Obtained 5 stack frames: 0x5589f7dcfcb8 0x7f5f1fa360c0 0x5589f7d7942a 0x7f5f1fa170b3 0x5589f7d7a15e
generate_proxy_mesh(+0x6ccb8)[0x5589f7dcfcb8]
/lib/x86_64-linux-gnu/libc.so.6(+0x430c0)[0x7f5f1fa360c0]
generate_proxy_mesh(+0x1642a)[0x5589f7d7942a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f5f1fa170b3]
generate_proxy_mesh(+0x1715e)[0x5589f7d7a15e]
Segmentation fault

how can I solve this problem, thx

**Comment by rebecca0011** [comment]
I have the same problem as you. Could you plz give me some advice
