### ISSUE TITLE
The evaluation tool doesn't work

### ISSUE THREAD

**Issue by whatseven** [nmoehrle/uavmvs#4]
I found the Evaluation Tools in the website. After reading the README, I use the trajectory provided in NY-1 and generate the image successfully. Then I import the images and reconstruct a model using [Reality Capture ](https://www.capturingreality.com/).

After that, I want to use the evaluation tools to evaluate the model. So I can evaluate my own trajectory. Here is my workflow of the reconstruct model:
```
    mesh=NY-1.ply
    alignMesh=alignMesh.ply
    gtMesh=NY-1.bin

    ./estimate_transform-mesh $mesh $gtMesh --transform=Talign.m
    ./convert-mesh $mesh $alignMesh --transform=Talign.m

    ./estimate_transform-mesh $alignMesh $gtMesh --transform=Talign.m
    ./convert-mesh $alignMesh $alignMesh --transform=Talign.m

    ./estimate_transform-mesh $alignMesh $gtMesh --transform=Talign.m
    ./convert-mesh $alignMesh $alignMesh --transform=Talign.m

    ./evaluate_reconstruction $alignMesh $gtMesh
```

After that I found the evaluation scores are very low, only 0.00267581 completeness when 0.0075. So i'm wondering if the `convert` is not work. Because no matter how many times I use the `convert` tools, it's average distance is the same.(0.09 for the gesox-mesh_orig.ply, and 0.12 for the model reconstructed by the images provided in the dataset).

Did I misuse the tools?

**Comment by nmoehrle** [comment]
The estimate_transform-mesh is only able to align already roughly aligned meshes, it's an implementation of iterative closest point (ICP). If the meshes are not roughly aligned beforehand it will converge to a wrong local minima, but does this deterministically so multiple invocations should not change the result.

How well is the alignment of the meshes before the invocation of the app?

**Comment by whatseven** [comment]
I got it. I import the flight data into my reconstruction tools and it works. The reconstructed model is belong the input data's coordinates. Thanks for your explanation!

**Comment by szx0112** [comment]
Hi @nmoehrle  @whatseven  how can we find the initial 2.5D meshes of the simulated scenes (e.g. NY-1) for oblique or optimized trajectory generation? I can only find the ground truth model in bin file. 

Do we assume a simple 2.5D mesh is given as input of this method? But I cannot locate the in the repository. Any comment is really appreciated.

**Comment by HZhang1003** [comment]
Hello, I have reconstructed the mesh model just like you. Now I want to compare my mesh with ground truth, but I can't find the scene binary file (e.g. NY-1.bin) anywhere. Could you tell me where the file is?

Looking forward to your reply. Thank you.
