### ISSUE TITLE
Build error inside "eval.make"

### ISSUE THREAD

**Issue by takavfx** [nmoehrle/uavmvs#6]
My test environment is Ubuntu 18.04 with cuda 9.1.85.

I've got this error at uavmvs make.

```
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00005a74_00000000-6_bvh_tree.cpp1.ii".
Compilation terminated.
eval.make:160: recipe for target 'obj/debug/eval/bvh_tree.o' failed
make[1]: *** [obj/debug/eval/bvh_tree.o] Error 1
Makefile:190: recipe for target 'eval' failed
make: *** [eval] Error 2
```

Is there any suggestion to solve this?

**Comment by takavfx** [comment]
It seems this is due to CUDA version mismatching.
We shouldn't run `sudo apt-get install nvidia-cuda-toolkit` without thinking about the environment.

**Comment by silence401** [comment]
> It seems this is due to CUDA version mismatching.
> We shouldn't run `sudo apt-get install nvidia-cuda-toolkit` without thinking about the environment.

Did you solve this problem,could you please tell me how to solve this problem
