### ISSUE TITLE
make error: util/endian.h: No such file or directory

### ISSUE THREAD

**Issue by szx0112** [nmoehrle/uavmvs#9]
All dependencies are installed, and I use ubuntu 16.04 and cuda-10.0. Any comment is appreciate.

Error message shows below:

==== Building fmt (debug) ====
==== Building sim (debug) ====
==== Building utp (debug) ====
==== Building eval (debug) ====
==== Building template (debug) ====
==== Building interop (debug) ====
==== Building generate_sphere_mesh (debug) ====
==== Building generate_aabb_mesh (debug) ====
==== Building convert-mesh (debug) ====
==== Building normalize-mesh (debug) ====
==== Building colorize-mesh (debug) ====
==== Building estimate_transform-mesh (debug) ====
==== Building convert-image (debug) ====
==== Building normalize-image (debug) ====
==== Building colorize-image (debug) ====
==== Building convert-scene (debug) ====
==== Building evaluate-scene (debug) ====
==== Building annotate-scene (debug) ====
==== Building estimate_transform-scene (debug) ====
==== Building reduce_randomly (debug) ====
==== Building deduce_bundle (debug) ====
==== Building match-scene (debug) ====
==== Building convert-cloud (debug) ====
==== Building convert-volume (debug) ====
==== Building normalize-volume (debug) ====
==== Building generate-trajectory (debug) ====
==== Building shorten-trajectory (debug) ====
==== Building interpolate-trajectory (debug) ====
==== Building evaluate-trajectory (debug) ====
==== Building determine_matching_mask (debug) ====
==== Building estimate_ground_plane (debug) ====
==== Building generate_texture (debug) ====
==== Building generate_gcp_bundle (debug) ====
==== Building generate_proxy_mesh (debug) ====
==== Building generate_proxy_cloud (debug) ====
==== Building generate_guidance_volume (debug) ====
==== Building generate_initial_trajectory (debug) ====
==== Building selector (debug) ====
==== Building simulator (debug) ====
==== Building visualizer (debug) ====
==== Building plan_trajectory (debug) ====
==== Building capture_trajectory (debug) ====
==== Building optimize_trajectory (debug) ====
==== Building evaluate_trajectory (debug) ====
==== Building evaluate_heuristic (debug) ====
evaluate_heuristic.cu
nvcc warning : Resource usage is not shown as the final resource allocation is not done.
In file included from ../apps/evaluate_heuristic/evaluate_heuristic.cu:16:0:
../libs/util/numpy_io.h:12:25: fatal error: util/endian.h: No such file or directory
compilation terminated.
evaluate_heuristic.make:158: recipe for target 'obj/debug/evaluate_heuristic/evaluate_heuristic.o' failed
make[1]: *** [obj/debug/evaluate_heuristic/evaluate_heuristic.o] Error 1
Makefile:436: recipe for target 'evaluate_heuristic' failed
make: *** [evaluate_heuristic] Error 2

**Comment by nmoehrle** [comment]
Seams like a mistake on my side the correct header since about a year ago is "until/system.h"
